name: jao-Super-Achievement2
main: com.jaoafa.jaosuperachievement2.Main
version: 2021.04.02_00.04
description: jao-Super-Achievement2
database: true
api-version: 1.16
author: mine_book000
commands:
  jsa:
    description: jaoSuperAchievement GUIを開きます。
    usage: /<command>
    permission: jaosuperachievement.jsa
    permission-message: You do not have permission to perform this command.
  jaosuperachievement2:
    description: jaoSuperAchievement2のリリース情報を表示します。
    usage: /<command>
    permission: jaosuperachievement.jaosuperachievement2
    permission-message: You do not have permission to perform this command.
