name: jao-Super-Achievement2
main: com.jaoafa.jaoSuperAchievement2.Main
version: 2020.04.24_10.26
description: jao-Super-Achievement2
database: true
author: mine_book000
commands:
  jsa:
    description: jaoSuperAchievement GUIを開きます。
    usage: /<command>
    permission: jaosuperachievement.jsa
    permission-message: You do not have permission to perform this command.
